# -*- coding: utf-8 -*-
"""DataCollection02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m0AwqFXDXXjm6Uy3iaiPseyMjzPiayB-
"""

from bs4 import BeautifulSoup

html = """
<html>
<head>
<title>스크레이핑 실습</title>
</head>
<body>
<h1 id="univ">인하대학교</h1>
<p>웹스크레이핑</p>
<p id="contents">넘파이, 판다스, NLP ... </p>
</body>
</html>
"""

soup = BeautifulSoup(html, 'html.parser')
university = soup.find(id='univ')
contents = soup.find(id='contents')

print(contents.string)
print(university.string)

from bs4 import BeautifulSoup

html = """
<html>
<head>
<title>스크레이핑 실습</title>
</head>
<body>
<a href="http://www.inha.ac.kr">인하대학교</a><br>
<a href="http://www.harvard.edu">하버드대학교</a>
</body>
</html>
"""
soup = BeautifulSoup(html, 'html.parser')
urls = soup.find_all("a")
#print(urls)
for url in urls:
  print(f"{url.string}의 url주소는 {url.attrs['href']}입니다.")

import urllib.request
from bs4 import BeautifulSoup

api = 'https://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp'
urls = urllib.request.urlopen(api).read()
soup = BeautifulSoup(urls, 'html.parser')

cities = soup.find_all("city")
#print(len(cities))
# wfs = soup.find_all("wf")
# wfs.pop(0)
datas = soup.find_all("data")

for i in range(len(cities)):
  #print(f"{cities[i].string}의 날씨는 {wfs[i*13].string}입니다")
  print(f"{cities[i].string}의 날씨는 {datas[i*13].find('wf').string}입니다")

!pip install datasets

from datasets import load_dataset

ds = load_dataset('squad')
print(ds)

import urllib.request
from bs4 import BeautifulSoup
import pandas as pd
import datetime

shops = list()

for i in range(1, 49):
    url = f"https://www.hollys.co.kr/store/korea/korStore2.do?pageNo={i}&sido=&gugun=&store="
    print(url)
    page = urllib.request.urlopen(url)
    soup = BeautifulSoup(page, "html.parser")
    tbody = soup.find('tbody')
    trs = tbody.find_all('tr')  # -> list

    for tr in trs:
        tds = tr.find_all('td')
        shop_name = tds[1].string  # 매장명
        shop_addr = tds[3].string  # 주소
        shop_phone = tds[5].string  # 전화번호
        shops.append([shop_name]+[shop_addr]+[shop_phone]+[datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")])  # 2d list

print(shops)
hollys_df = pd.DataFrame(shops, columns=('매장명','주소','전화번호','일시'))
hollys_df.to_csv('holly.csv', mode='w', index=True, encoding='cp949')